# Generated by Django 4.2.7 on 2023-11-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('pnumber', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('gmail', models.EmailField(blank=True, max_length=50)),
                ('courses', models.CharField(max_length=70)),
                ('vehicleclass', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
