# Generated by Django 4.2.7 on 2023-11-28 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(default=' ', max_length=50)),
                ('constituency', models.CharField(default=' ', max_length=50)),
                ('ward', models.CharField(default=' ', max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('sub_location', models.CharField(max_length=50, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50)),
                ('surname', models.CharField(default=' ', max_length=50)),
                ('other_names', models.CharField(default=' ', max_length=50)),
                ('regno', models.CharField(max_length=10, unique=True)),
                ('course', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_name', models.CharField(max_length=50)),
                ('test_date', models.CharField(max_length=50)),
                ('test_time', models.CharField(max_length=50)),
                ('test_venue', models.CharField(max_length=10)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('comment', models.CharField(max_length=10)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=50, null=True)),
                ('address', models.ManyToManyField(blank=True, to='portals.location')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_date', models.CharField(max_length=50)),
                ('exam_time', models.CharField(max_length=50)),
                ('exam_venue', models.CharField(max_length=10)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
