# Generated by Django 4.2.7 on 2023-11-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='ref',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
