# Generated by Django 4.2.7 on 2023-11-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='date',
            new_name='test_date',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='time',
            new_name='test_time',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='venue',
            new_name='test_venue',
        ),
    ]
