# Generated by Django 4.2.7 on 2023-11-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_rename_date_test_test_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date',
            new_name='exam_date',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam',
            new_name='exam_name',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='time',
            new_name='exam_time',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='venue',
            new_name='exam_venue',
        ),
    ]
