# Generated by Django 4.2.7 on 2023-11-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_rename_date_exam_exam_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
    ]
