# Generated by Django 4.2.7 on 2023-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_remove_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ref', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('debit', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
